# This is a basic workflow that is manually triggered

name: Update Notion progress

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  issues:
    types: [closed]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  notion:
    name: update notion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm install @notionhq/client
      
        
        env: 
            GITHUB_KEY: ${{ secrets.JSL_GITHUB_KEY }}
            NOTION_KEY: ${{ secrets.JSL_NOTION_KEY }}
            NOTION_DATABASE_ID: ${{ secrets.JSL_NOTION_DB_ID }}
            GITHUB_REPO_OWNER: TunghaiTSM
            GITHUB_REPO_NAME: IOT-Final
      - run: node IOT-Final/index.js
